---
abstract: 'Protect your site from robots'
author:
  - 'Andrey Kostenko, C<< <andrey at kostenko.name> >>'
build_requires:
  Catalyst::Runtime: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-RateLimit
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.7
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
